# Generated by Django 5.2.8 on 2026-07-24 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animals',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('food', models.CharField(max_length=100)),
                ('habitat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='caretaker',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('caretaker_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='doner',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('doner_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('animal', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='enrollments',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoodb.animals')),
                ('caretaker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoodb.caretaker')),
                ('doner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoodb.doner')),
            ],
        ),
    ]
